// ---- Type metadata ----
export const TYPE_META = {
  READING_PASSAGE:        { label: 'Đoạn văn',           bg: '#dcfce7', color: '#15803d' },
  AUDIO_TRANSCRIPT:       { label: 'Nghe',                bg: '#dbeafe', color: '#1d4ed8' },
  STANDALONE:             { label: 'Câu độc lập',         bg: '#f3f4f6', color: '#374151' },
  DIAGRAM:                { label: 'Sơ đồ',               bg: '#fef9c3', color: '#a16207' },
  MAP:                    { label: 'Bản đồ',              bg: '#fce7f3', color: '#be185d' },
  MAP_LABELLING:          { label: 'Map Labelling',        bg: '#f0fdf4', color: '#166534' },
  IMAGE_NOTE_FORM:        { label: 'Ảnh + Note Form',     bg: '#e0e7ff', color: '#4338ca' },
  TABLE_COMPLETION:       { label: 'Table Completion',     bg: '#e0e7ff', color: '#4338ca' },
  TABLE:                  { label: 'Bảng',                bg: '#e0e7ff', color: '#4338ca' },
  MATCHING_HEADING:       { label: 'Matching Headings',   bg: '#fff7ed', color: '#c2410c' },
  DRAG_MATCHING:          { label: 'Drag Matching',        bg: '#f0fdf4', color: '#166534' },
  SUMMARY_COMPLETION:     { label: 'Summary Completion',  bg: '#f0f9ff', color: '#0369a1' },
  SUMMARY_COMPLETION_SELECT: { label: 'Summary (Select)',  bg: '#fef3c7', color: '#92400e' },
  NOTE_COMPLETION:        { label: 'Note Completion',      bg: '#fefce8', color: '#854d0e' },
  MULTIPLE_CHOICE_GROUP:  { label: 'Multiple Choice',      bg: '#ffe4e6', color: '#be123c' },
  MULTIPLE_CHOICE_MULTI:  { label: 'MC Nhiều đáp án',       bg: '#fce7f3', color: '#9d174d' },
  TRUE_FALSE_NG:          { label: 'True/False/NG',      bg: '#eff6ff', color: '#1d4ed8' },
  SENTENCE_COMPLETION:    { label: 'Sentence Completion',  bg: '#ecfdf5', color: '#065f46' },
  SHORT_ANSWER_GROUP:     { label: 'Short Answer',         bg: '#f0fdf4', color: '#166534' },
  FLOW_CHART:             { label: 'Flow-chart',           bg: '#f0fdfa', color: '#0f766e' },
  FLOW_CHART_TEXT:        { label: 'Flow-chart (Text)',    bg: '#f0fdfa', color: '#0f766e' },
  MATCHING_FEATURES:      { label: 'Matching Features',    bg: '#f3e8ff', color: '#7c3aed' },
  MATCHING_FILLABLE:      { label: 'Matching (Fill-in)',   bg: '#fef3c7', color: '#92400e' },
  MATCHING_HEADINGS_FILLABLE: { label: 'Match Headings (Fill)', bg: '#fed7aa', color: '#9a3412' },
  FILL_BLANK_DRAG:        { label: 'Fill Blank (Drag)',    bg: '#d1fae5', color: '#065f46' },
  SENTENCE_COMPLETION_DRAG: { label: 'Sentence (Drag)',    bg: '#ccfbf1', color: '#0f766e' },
  SUMMARY_COMPLETION_DRAG: { label: 'Summary (Drag)',      bg: '#cffafe', color: '#0e7490' },
  NOTE_COMPLETION_DRAG:   { label: 'Note (Drag)',          bg: '#fef08a', color: '#713f12' },
  SHARED_OPTIONS_DROPDOWN:{ label: 'Dropdown chung',       bg: '#e0f2fe', color: '#0369a1' },
  WRITING_TASK:           { label: 'Writing',              bg: '#fef9c3', color: '#a16207' },
  SPEAKING_INTERVIEW:     { label: 'Part 1 - Interview',  bg: '#fce7f3', color: '#be185d' },
  SPEAKING_CUECARD:       { label: 'Part 2 - Cue Card',   bg: '#fdf4ff', color: '#7e22ce' },
  SPEAKING_DISCUSSION:    { label: 'Part 3 - Discussion', bg: '#ede9fe', color: '#6d28d9' },
  SPEAKING_PART1:         { label: 'Speaking Part 1',      bg: '#dbeafe', color: '#1e40af' },
  SPEAKING_PART2:         { label: 'Speaking Part 2',      bg: '#fef3c7', color: '#b45309' },
  SPEAKING_PART3:         { label: 'Speaking Part 3',      bg: '#e0e7ff', color: '#4338ca' },
  SPEAKING_PART0:         { label: 'Part 0 - Cấu hình',    bg: '#fff7ed', color: '#c2410c' },
  SPEAKING_NEW_FORMAT:    { label: 'Cấu hình Đề (Dynamic)', bg: '#fdf2f8', color: '#be185d' },
};
