#!/bin/bash

echo "=== CHECK API ERROR ==="
echo ""
echo "Hướng dẫn kiểm tra lỗi API:"
echo ""
echo "1. Mở browser DevTools (F12)"
echo "2. Chuyển sang tab Network"
echo "3. Filter: XHR hoặc Fetch"
echo "4. Click nút Lưu trong TestBuilder"
echo "5. Tìm request: POST /test-builder/save-full"
echo "6. Click vào request đó"
echo "7. Xem tab Response để thấy lỗi"
echo ""
echo "Các lỗi thường gặp:"
echo "- 400 Bad Request: Dữ liệu không hợp lệ"
echo "- 401 Unauthorized: Chưa đăng nhập"
echo "- 403 Forbidden: Không có quyền"
echo "- 500 Internal Server Error: Lỗi server"
echo ""
echo "Nếu thấy lỗi, copy message và paste cho tôi"
echo ""
