#!/bin/bash

echo "=== VERIFY FIX: Table Completion Answer Persistence ==="
echo ""
echo "Test scenario:"
echo "1. Tạo table với [blank]"
echo "2. Nhập đáp án 'test123'"
echo "3. Tick checkbox 'Bỏ qua hoa/thường'"
echo "4. Click nút Lưu"
echo "5. Reload trang"
echo "6. Kiểm tra đáp án 'test123' vẫn còn"
echo ""
echo "Expected: Đáp án được giữ nguyên sau khi lưu và reload"
echo ""
echo "Nếu đáp án bị mất → questionsRef.current chưa được dùng đúng chỗ"
echo ""
