#!/bin/bash

echo "=== QUICK TEST: Answer Update Issue ==="
echo ""
echo "Test Steps:"
echo "1. Mở browser: http://localhost:5173/test-builder"
echo "2. Tạo Table Completion block"
echo "3. Nhập '[blank]' vào cell"
echo "4. Nhập đáp án 'test1' vào ô đáp án"
echo "5. Mở Console (F12)"
echo "6. Sửa đáp án thành 'test2'"
echo ""
echo "Expected in Console:"
echo "  Updating answer: { qId: ..., newAnswer: 'test2', updatedQuestions: [...] }"
echo ""
echo "Expected in UI:"
echo "  Input value changes to 'test2'"
echo ""
echo "If log appears but UI doesn't update:"
echo "  → React rendering issue"
echo ""
echo "If log doesn't appear:"
echo "  → Event handler not called"
echo ""
